apiVersion: v1
clusters:
  - cluster:
      server: http://127.0.0.1:8080
    name: kwok
contexts:
  - context:
      cluster: kwok
      user: ""
    name: kwok
current-context: "kwok"
kind: Config
preferences: {}
