name: Force update helm chart

on:
  workflow_dispatch:

jobs:
  is-chart-working:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare.outputs.version }}
    steps:
      - name: Clone helm chart repository
        uses: actions/checkout@v3
        with:
          path: ./helm-charts
      - name: Set variables
        id: prepare
        shell: bash
        run: |
          version=$(yq -e .appVersion helm-charts/rocketchat/Chart.yaml)
          echo "version=$version" >>$GITHUB_OUTPUT
      - name: Clone tests
        uses: actions/checkout@v3
        with:
          repository: debdutdeb/rocket.chat.tests
          path: tests
          submodules: true
      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
      - name: Run tests
        shell: bash
        env:
          ROCKETCHAT_MAX_ATTEMPTS: 250
          ROCKETCHAT_TAG: ${{ steps.prepare.outputs.version }}
        run: |
          sudo apt-get install --no-install-recommends -y jo jq
          export ROCKETCHAT_CHART_DIR="$(realpath ./helm-charts/rocketchat)"
          cd tests &&
            bash run_k8s.bash

      - name: Notify core team
        if: always()
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        with:
          job_name: '*Helm chart ${{ steps.prepare.outputs.version }} tests*'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          type: ${{ job.status }}
          mention: 'debdut.chakraborty'
          mention_if: failure

  update-release:
    needs:
      - is-chart-working
    runs-on: ubuntu-latest
    steps:
      - name: Clone helm repo
        uses: actions/checkout@v2
        with:
          path: ./helm-charts

      - name: Clone helm repo (gh-pages)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./gh-pages

      - name: Update chart and rocketchat versions
        shell: bash
        id: version
        run: |
          sed -i -r '/^appVersion:/ s/ .+/ ${{ needs.is-chart-working.outputs.version }}/' ./helm-charts/rocketchat/Chart.yaml
          sed -i -r '/^version:/ s/ .+/ ${{ needs.is-chart-working.outputs.version }}/' ./helm-charts/rocketchat/Chart.yaml

      - name: Pull dependencies
        shell: bash
        run: helm dependency update ./helm-charts/rocketchat

      - name: Generate helm package
        shell: bash
        run: helm package ./helm-charts/rocketchat -d gh-pages/charts/

      - name: Re-generate helm index
        run: helm repo index ./gh-pages/

      - name: Push to master
        uses: EndBug/add-and-commit@v9
        with:
          add: "rocketchat/Chart.yaml"
          cwd: helm-charts
          message: "Chore: bump Rocket.Chat and chart version to ${{ needs.is-chart-working.outputs.version }}"
          push: true

      - name: Push to gh-pages
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          cwd: gh-pages
          message: "Chore: bump Rocket.Chat and chart version to ${{ needs.is-chart-working.outputs.version }}"
          push: true
      
      - name: Create a release with artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ format('./gh-pages/charts/rocketchat-{0}.tgz', needs.is-chart-working.outputs.version) }}
          prerelease: false
          name: ${{ needs.is-chart-working.outputs.version }}
          tag_name: ${{ needs.is-chart-working.outputs.version }}
          body: ${{ format('https://github.com/RocketChat/Rocket.Chat/releases/{0}', needs.is-chart-working.outputs.version) }}
          draft: false

      - name: Notify core team
        if: always()
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        with:
          job_name: ${{ format('*Helm {0} release*', needs.is-chart-working.outputs.version) }}
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          type: ${{ job.status }}
          mention: 'debdut.chakraborty'
          mention_if: failure
